The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) CCconfig         4) imkl/2020.1.217    7) libfabric/1.10.1
  2) gentoo/2020      5) intel/2020.1.217   8) openmpi/4.0.3
  3) gcccore/.9.3.0   6) ucx/1.8.0          9) StdEnv/2020

The following have been reloaded with a version change:
  1) python/3.7.9 => python/3.8.10


Inactive Modules:
  1) ipykernel/2022a     2) libffi/3.3

The following have been reloaded with a version change:
  1) StdEnv/2020 => StdEnv/2016.4
  2) gcccore/.9.3.0 => gcccore/.5.4.0
  3) imkl/2020.1.217 => imkl/11.3.4.258
  4) intel/2020.1.217 => intel/2016.4
  5) openmpi/4.0.3 => openmpi/2.1.1
  6) python/3.8.10 => python/3.7.4
  7) scipy-stack/2022a => scipy-stack/2019a

Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx512, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/scikit_learn-0.23.0+computecanada-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: threadpoolctl>=2.0.0 in /lustre03/project/6043437/mheuill/MYENV/lib/python3.7/site-packages (from scikit-learn) (3.1.0+computecanada)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/joblib-1.2.0+computecanada-py3-none-any.whl
Requirement already satisfied: scipy>=0.19.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: numpy>=1.13.3 in /lustre03/project/6043437/mheuill/MYENV/lib/python3.7/site-packages (from scikit-learn) (1.20.2+computecanada)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/lustre03/project/6043437/mheuill/MYENV/lib/python3.7/site-packages/threadpoolctl-3.1.0+computecanada.dist-info/METADATA'

/lustre03/project/6043437/mheuill/MYENV/lib/python3.7/site-packages/setuptools/_importlib.py:23: UserWarning: `importlib-metadata` version is incompatible with `setuptools`.
This problem is likely to be solved by installing an updated version of `importlib-metadata`.
  warnings.warn(msg)  # Ensure a descriptive message is shown.
Traceback (most recent call last):
  File "./partial_monitoring/experiment.py", line 27, in <module>
    from sklearn.preprocessing import PolynomialFeatures
ModuleNotFoundError: No module named 'sklearn'
